
name: Helpers
on:
  workflow_dispatch:

env:
  app: Accept:application/vnd.github.v3+json
  base_url: $GITHUB_API_URL/repos/$GITHUB_REPOSITORY/actions/runs
  AUTH: ${{ secrets.GITHUB_TOKEN }}
  no_instances: 6
  
defaults:
  run:
    shell: bash -leo pipefail {0}

jobs:
  pre:
    name: Preprocess
    runs-on: ubuntu-20.04

    steps:
    - name: Share helper id
      run: echo -n ${{ github.run_id }} >~/id_file

    - uses: actions/cache@v2
      with:
        path: ~/id_file
        key: helperid-${{ github.event.workflow_run.id }}
        
    - name: print id file
      run: cat id_file

  repocheck:
    name: Repo check
    runs-on: ubuntu-20.04

    steps:
    - name: Check up-to-dateness and post comment
      run: |
        comment="random comment"
        echo "comment is $comment"
        if [[ -n $comment ]]; then
          echo -n "failure" >~/repocheck_file
        else
          echo -n "success" >~/repocheck_file
        fi
    - uses: actions/cache@v2
      with:
        path: ~/repocheck_file
        key: repocheck-${{ github.event.workflow_run.id }}

    - name: print repocheck file
      run: cat repocheck_file
